### ISSUE TITLE
encoder.h is missing

### ISSUE THREAD

**Issue by ajaisehgal** [synfinatic/esp-dsc#1]
@synfinatic esp_dsc.ino includes Encoder.h which does not appear to be checked into the source.  Ok read in your testing code that I need to use https://github.com/PaulStoffregen/Encoder.  Maybe should be in the readme.

**Comment by synfinatic** [comment]
Intended.  You should install the [Encoder library](https://github.com/PaulStoffregen/Encoder) either manually or via the Arduino IDE
